### ISSUE TITLE
404 issue

### ISSUE THREAD

**Issue by farazilu** [rgrove/rawgit#102]
I noticed that some time cdn.rawgit.com send 404 error randomly.  
I am using this link
https://cdn.rawgit.com/liabru/jquery-match-height/master/jquery.matchHeight-min.js

**Comment by neoascetic** [comment]
There is no `query.matchHeight-min.js` file in the original repo anymore.

**Comment by farazilu** [comment]
Hi here is the link of file.
https://github.com/liabru/jquery-match-height/blob/master/jquery.matchHeight.js
when i pasted this link in RawGit it generated this link
https://cdn.rawgit.com/liabru/jquery-match-height/master/jquery.matchHeight.js

Am I doing some thing wrong?

**Comment by farazilu** [comment]
sorry!
Yes -min file is removed now.. my bad.
