### ISSUE TITLE
HTTP 500

### ISSUE THREAD

**Issue by bestpika** [rgrove/rawgit#107]
[This user's](http://github.com/googlemaps/v3-utility-library) file caused http 500.
ex. https://cdn.rawgit.com/googlemaps/v3-utility-library/master/markerclustererplus/src/data.json

**Comment by WiBla** [comment]
It's not related to any file, it's a server issue, try any link based on rawgit, it will not work.
There must be an error somewhere server-side, wait for the dev to look for it. It's the only solution.

**Comment by neoascetic** [comment]
While you are waiting for fix, you may try out [raw.githack.com](https://raw.githack.com) as an alternative. It doesn't provide CDN, though. [Here is your link](https://raw.githack.com/googlemaps/v3-utility-library/master/markerclustererplus/src/data.json).

**Comment by hammad417** [comment]
Thanks for the alternate.

**Comment by rgrove** [comment]
Sorry everyone. RawGit is back up now.

DigitalOcean began experiencing a DNS connectivity issue very early this morning (in my timezone) while I slept, which prevented RawGit from being able to make DNS lookups, which in turn prevented it from being able to contact GitHub. DigitalOcean still hasn't resolve this issue, but I've swapped out RawGit's nameservers with working ones to mitigate it.
