### ISSUE TITLE
rawgit.com website is down.

### ISSUE THREAD

**Issue by vishknetworks** [rgrove/rawgit#108]
returns 500 error

**Comment by MacKentoch** [comment]
Who pushed the red button?

No seriously what is going on?

**Comment by captbaritone** [comment]
I'm getting 400 error. I'm happy to help debug if needed. Thanks for the great service!

**Comment by captbaritone** [comment]
Sorry 500 error (mobile fail)

**Comment by hammad417** [comment]
yes its down. still getting 500

**Comment by coryshaw1** [comment]
Still down here. The error message "Shit." makes me feel a little better though

**Comment by neoascetic** [comment]
While you are waiting for fix, you may try out raw.githack.com as an alternative. It doesn't provide CDN yet, though.

**Comment by neoascetic** [comment]
See also #107

**Comment by ApexaGA** [comment]
it work for me, now

**Comment by captbaritone** [comment]
Works for me as well :clap:

**Comment by rgrove** [comment]
Sorry everyone. RawGit is back up now.

DigitalOcean began experiencing a DNS connectivity issue very early this morning (in my timezone) while I slept, which prevented RawGit from being able to make DNS lookups, which in turn prevented it from being able to contact GitHub. DigitalOcean still hasn't resolved this issue, but I've swapped out RawGit's nameservers with working ones to mitigate it.

**Comment by djdeo** [comment]
It's now down again, error message `ERR_CONNECTION_TIMED_OUT`, any alternatives would be appreciated...
