### ISSUE TITLE
Explain errors when improper URLs have been pasted

### ISSUE THREAD

**Issue by kevinSuttle** [rgrove/rawgit#110]
<img width="1277" alt="screen shot 2016-04-19 at 11 26 17 am" src="https://cloud.githubusercontent.com/assets/95672/14644936/bc715c7a-0621-11e6-9e78-f4c260c586a7.png">

Nothing in the console, 2 browsers tried. No errors or explanations.

**Comment by rgrove** [comment]
You're right, the widget could be more helpful.

In the meantime, I've [added an item to the FAQ](https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#does-rawgit-support-gists) explaining how to get the raw URL for a gist file, which is what RawGit needs.

**Comment by kevinSuttle** [comment]
Ah, thanks. That's what I missed.

**Comment by rgrove** [comment]
I've updated the URL formatter. When a non-raw gist URL is pasted, it now fetches the raw gist URL from the GitHub API. Hopefully that's the end of the gist URL confusion.

**Comment by kevinSuttle** [comment]
Thanks Ryan!
