### ISSUE TITLE
Force refresh a cached URL 

### ISSUE THREAD

**Issue by feross** [rgrove/rawgit#111]
Hey -- we flubbed up and somehow a really huge version of our badge got cached by rawgit: https://cdn.rawgit.com/feross/standard/master/badge.svg

It's messing up 100s, maybe 1000s, of readme files. (See https://github.com/feross/standard/issues/494) 

Is there any way we can force the cache to be cleared?

**Comment by rgrove** [comment]
😲 😆 

I've purged that URL, but be warned that [CDN URLs are always cached permanently](https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file). If you need to be able to serve updated versions of the badge without requiring people to change the URL they're using, RawGit may not be the best choice.

**Comment by feross** [comment]
Yep -- I understand that. Will move to our own url for the badge -- but thanks for fixing all the ones that are already out there!

**Comment by feross** [comment]
Also, thanks for the fast response time!

**Comment by feross** [comment]
@rgrove Is it possible that you may have forgotten to clear one of the international caches? Like in Australia? See https://github.com/feross/standard/issues/494#issuecomment-213992194 who is still seeing the old image.

Thanks and sorry for being a hassle.

**Comment by rgrove** [comment]
@feross I've purged the cache again. Unfortunately I don't have granular control over the individual edge nodes -- it's just one big purge button. Hopefully it works this time.

One other thing that could cause this is if there's a caching proxy between MaxCDN and the user(s) who are still seeing the old image. That proxy would still be respecting the far-future max-age on the file, and purging MaxCDN won't help.

**Comment by feross** [comment]
@rgrove Thanks!

**Comment by dcousens** [comment]
@rgrove hasn't purged for me :cry:

**Comment by rgrove** [comment]
@dcousens If purging hasn't solved the problem, then the file is most likely cached somewhere between you and the CDN. I'm afraid there's nothing more I can do. Sorry.

If you have control over the site that's displaying the image, then you can fix this by changing the URL to use a tag or commit ref in place of the branch name, like this: 

<https://cdn.rawgit.com/feross/standard/f61dd29/badge.svg>
