### ISSUE TITLE
Incomplete source

### ISSUE THREAD

**Issue by smartclash** [rgrove/rawgit#113]
I actually downloaded your source and it works fine. But I want to host the files in my maxcdn account and not yours.

I think you have done some scripting in the cdn.rawgit.com and that's why it can fetch files correctly. Please either publish the whole source code or explain how to use it with maxcdn.

Anyways, I like your idea. 👍

**Comment by rgrove** [comment]
RawGit's MaxCDN config doesn't do anything special. It just requests files from RawGit with a `RawGit-CDN: Yup` header, which tells RawGit not to impose traffic limitations on the CDN requests.

**Comment by smartclash** [comment]
@rgrove can you please tell me how to install it to my cdn? i always get a 404. I am too using maxcdn

**Comment by rgrove** [comment]
There's nothing to install on MaxCDN. You need to run RawGit on your own server (this is called the "origin server"), then create a MaxCDN pull zone and configure it to forward requests to your origin server when the CDN doesn't have a file in its cache.

Please contact MaxCDN for help configuring their service.
