### ISSUE TITLE
How to make webfonts work?

### ISSUE THREAD

**Issue by oblitum** [rgrove/rawgit#116]
I have some web fonts hosted on S3 with the bucket with the following CORS configuration:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>http://bl.ocks.org</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://rawgit.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://cdn.rawgit.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://nosubstance.me</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
    </CORSRule>
    <CORSRule>
        <AllowedOrigin>http://oblita.com</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>HEAD</AllowedMethod>
    </CORSRule>
</CORSConfiguration>
```

My fonts work fine when accessed from all origins except from rawgit. I've tried a lot to figure it out but I coudn't, any help?

Notice that per [S3 CORS docs](https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html#how-do-i-enable-cors), http means http plus https. Despite this, I've tried all combinations.

I'm trying to access:

- https://s3.amazonaws.com/oblitum-fonts/monofur-webfont.eot
- https://s3.amazonaws.com/oblitum-fonts/monofur-webfont.svg
- https://s3.amazonaws.com/oblitum-fonts/monofur-webfont.ttf
- https://s3.amazonaws.com/oblitum-fonts/monofur-webfont.woff
- https://s3.amazonaws.com/oblitum-fonts/monofur-webfont.woff2

This is a sample webpage that should have been loading them but doesn't:

https://cdn.rawgit.com/oblitum/615f668bd2b173c3da677e038e2ac161/raw/215ad8a676528a2731ed8febbae56600f53603f7/skynet-haskell.html

**Comment by neoascetic** [comment]
No, you are trying to access not "httpS://s3.amazonaws.com/oblitum-fonts/monofur-webfont.eot" and others, but their non-secure HTTP version. Browser disallows you to load insecure stuff on a secured page. Try to use a schema agnostic URLs or simply always use HTTPS.

**Comment by oblitum** [comment]
@neoascetic ops... dumb me. Thank you.
