### ISSUE TITLE
CORS request blocked

### ISSUE THREAD

**Issue by retog** [rgrove/rawgit#117]
Firefox blocks requests with the following error message:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://cdn.rawgit.com/rdf2h/rdf2h.github.io/v0.0.1/2015/rdf2h-points.ttl. (Reason: CORS header 'Access-Control-Allow-Origin' missing).

I see the `Access-Control-Allow-Origin` is present on the https resource but not on the http resource, could you add this?

**Comment by rgrove** [comment]
Yesterday RawGit began redirecting all HTTP requests to HTTPS. Requesting an HTTPS URL instead of HTTP should resolve this. Let me know if you try that and still have trouble.

**Comment by Multiply** [comment]
I commented on the same thing here: https://github.com/rgrove/rawgit/issues/114#issuecomment-222474418

It's a problem for us, as we use a simple tool that requests external websites to fetch data, and they don't support HTTPS and will not make the HTTPS move any time soon, either.

**Comment by neoascetic** [comment]
Does http://raw.githack.com work for you?

**Comment by Multiply** [comment]
@neoascetic It sure does. Is it going to be available 'permanently'?

**Comment by neoascetic** [comment]
I see no reasons to force HTTPS
