### ISSUE TITLE
rawgit doesn't follow redirects for renamed/moved repos

### ISSUE THREAD

**Issue by holic** [rgrove/rawgit#118]
I have a site using Chart.js, which was recently moved from nnnick/Chart.js to chartjs/Chart.js.

GitHub redirects the repo link to the new location: https://github.com/nnnick/Chart.js

However, rawgit serves a 404 which I didn't notice until a user alerted me to the charts on my page not loading.

**Comment by rgrove** [comment]
What's the exact URL that's returning a 404?

<https://rawgit.com/nnnick/Chart.js/master/dist/Chart.min.js> works for me.

**Comment by holic** [comment]
Ahh, I see. It looks like the directory structure of the project changed in a recent release. The URL I was working with is: https://cdn.rawgit.com/nnnick/Chart.js/master/Chart.min.js

It was my mistake to be using master rather than a commit/tag.
