### ISSUE TITLE
Gist URL error

### ISSUE THREAD

**Issue by Marsupio** [rgrove/rawgit#124]
When i paste my Gist file URL i get no links in rawgit.com
The URL is this:
https://gist.github.com/Marsupio/6bb446a5cc841d068bdb33136dda21b1#file-nodos-java

Is anything wrong?

**Comment by rgrove** [comment]
Please see https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#does-rawgit-support-gists
