### ISSUE TITLE
Show how to use commit-specific hashes

### ISSUE THREAD

**Issue by rjstone** [rgrove/rawgit#127]
I created an animated GIF to show people how to generate a URL with a commit hash. This may make a useful addition to the RawGit page so I figured I'd post it since showing this might help prevent any unhappy incidents with people using the proxy when they should be using the CDN.

![RawGit Animated GIF showing how to create URLs with commit specific hashes with a web browser.](https://cdn.rawgit.com/rjstone/rjstone.github.io/b63f8fe9032151e2e22b5893ceb7177744fe8e1a/img/RawGitLinking.gif)

There's a short blog post about it [here](https://codepen.io/rjstone/post/using-rawgit-to-serve-files)

**Comment by rgrove** [comment]
This is great. Thanks! I've [added it to the FAQ](https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#how-can-i-get-a-github-url-with-a-commit-hash-to-use-with-the-cdn).

**Comment by rjstone** [comment]
I also created a little shell script because trying to do this with a browser is annoying. This works in linux bash and gitbash in Windows.

https://gist.github.com/rjstone/3b6617155210357b20541bfc00ca4622

**Comment by rgrove** [comment]
Good stuff! Thanks for sharing.
