### ISSUE TITLE
Support Git-LFS files

### ISSUE THREAD

**Issue by wjdp** [rgrove/rawgit#128]
I've PDFs in my repo which I currently link to using the GitHub raw URL. These PDFs are stored using [Git LFS](https://git-lfs.github.com/) to prevent repo bloat. 
- Requesting these files through GitHub's `/raw/` urls work, obvs sans the correct mimetype
- Requesting them through RawGit returns the correct mimetype, but the LFS pointer file rather than the PDF

![image](https://cloud.githubusercontent.com/assets/1690934/18810718/3589a366-8295-11e6-9316-83747e5e2a68.png)

**Comment by subatomicglue** [comment]
I also have this problem.

Serving https://rawgit.com/subatomicglue/drummachine/master/index.html
Which does `XMLHttpRequest` to access https://rawgit.com/subatomicglue/drummachine/master/env9091.wav which doesn't work since it is stored in `git-lfs`.

**Comment by subatomicglue** [comment]
Solved it with 

https://crossorigin.me/https://media.githubusercontent.com/media/subatomicglue/drummachine/master/env9091.wav
