### ISSUE TITLE
cdn.rawgit.com 404 not working

### ISSUE THREAD

**Issue by gedas93** [rgrove/rawgit#129]
http://cdn.rawgit.com/ 404 not found. 
I know that this may be not a right place to post this, but I cannot reach cdn. it says 404 not found. some of my apps stopped working because of this. I hope it will be fixed as soon as possible. I guess that there is something wrong with nginx subnet configuration

**Comment by rgrove** [comment]
The CDN doesn't serve anything at '/', which is why that's a 404. It only serves file URLs, like https://cdn.rawgit.com/rgrove/rawgit/master/index.js

Everything is working fine as far as I can tell, but if you're having problems with a specific CDN URL, please post it and I'll investigate.
