### ISSUE TITLE
cdn.rawgit.com gives a 404

### ISSUE THREAD

**Issue by JonnoFTW** [rgrove/rawgit#131]
The CDN is down. Can you please rectify this ASAP.

**Comment by rgrove** [comment]
The CDN is not down. If you're having trouble, please provide a specific URL.

**Comment by JonnoFTW** [comment]
My bad, looks like a library I was using got `.gitignored` by the maintainer: https://github.com/codemirror/CodeMirror/commit/4cedb7e56ad865ac5825a18de2ddae65def32cce
