### ISSUE TITLE
anonymous gist returns 403

### ISSUE THREAD

**Issue by Haroenv** [rgrove/rawgit#132]
An anonymous gist like https://gist.githubusercontent.com/anonymous/030a2c860105e2e5bf709bf1ab68be37/raw/db29ef22641307d7fc3a8b1e480f46bfb9371938/index.html will return 403 Forbidden for it's equivalent rawgit url: http://rawgit.com/anonymous/030a2c860105e2e5bf709bf1ab68be37/raw/db29ef22641307d7fc3a8b1e480f46bfb9371938/index.html

This does work with non-anonymous gists.

**Comment by rgrove** [comment]
RawGit doesn't serve anonymous gists because they're frequently used for illegal or abusive content. Sorry.

**Comment by Haroenv** [comment]
No problem. Thi is totally reasonable
