### ISSUE TITLE
IPv6 issue

### ISSUE THREAD

**Issue by nakaruna** [rgrove/rawgit#133]
`cdn.rawgit` isn't support ipv6

**Comment by rgrove** [comment]
MaxCDN doesn't currently support IPv6. Unfortunately this isn't something RawGit has control over.

**Comment by tambry** [comment]
StackPath seems to have recently gotten IPv6 support. Could this issue be revisited?

**Comment by rgrove** [comment]
@tambry Can you point me to some documentation? I can't seem to find anything.

**Comment by tambry** [comment]
@rgrove Seems like they don't have any documentation for it. [BootstrapCDN](https://www.bootstrapcdn.com)'s endpoints use StackPath as their CDN provider and they mostly definitely work over IPv6. I'm guessing that it's a limited rollout for now and you'll need to message their support to move you over to a newer IPv6-capable endpoint.

**Comment by tambry** [comment]
@rgrove I think IPv6 is available now. [One of their marketing pages](https://www.stackpath.com/services/content-delivery-network-cdn/) now claims IPv6 and HTTP/2 support. I think moving to [their new StackPath 2.0 CDN infrastructure](https://www.stackpath.com/maxcdn/details/) might be necessary though.
