### ISSUE TITLE
Not Cleaning cache

### ISSUE THREAD

**Issue by krishnaTORQUE** [rgrove/rawgit#134]
Not Cleaning cache, when updating repository.

**Comment by rgrove** [comment]
https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#how-long-does-the-cdn-cache-files-how-can-i-make-it-refresh-my-file

**Comment by alanruttenberg** [comment]
Not trying to beat a dead horse, but it would be nice to be able to at least invalidate a cache entry. In case a mistake is made... 

An explicit invalidate (as opposed to automatic refresh) is more burden on the developer and less on the CDN. Which is in the right direction.

Consider it a feature request.

(not surprisingly, I made some mistakes before I understood the service well enough)

**Comment by rgrove** [comment]
@alanruttenberg You can explicitly invalidate a cache entry. Just change the URL.

There are a number of ways to change the URL:

-   You can make a new commit, then use the commit hash in the URL.
-   You can push a new tag, then use the tag in the URL.
-   You can push a new branch, then use the branch in the URL.

If you made a mistake and used the master branch in a CDN URL and then shared that URL with 3 million people, you have several more options:

-   Buy a DeLorean, turn it into a time machine, then go back in time and slap yourself before you have a chance to use the master branch in a CDN URL.
-   Buy a DeLorean, turn it into a time machine, then go 24 hours into the future, at which point your master branch CDN URL will have expired from the cache.
-   Skip the whole time machine thing and just watch Back to the Future 12.413793103 times, at which point your master branch CDN URL will have expired from the cache _and_ you'll have had a great time.

(In case it's not clear, I recently made a change that causes master branch CDN URLs to expire after 24 hours or 12.413793103 viewings of Back to the Future. Enjoy.)
