### ISSUE TITLE
It doesn't work for anonymous gist

### ISSUE THREAD

**Issue by rpgdev** [rgrove/rawgit#136]
It hasn't worked for any of the anonymous gist I've tried. I looked at the FAQ to see if this was by design but I didn't see anything. Example: https://gist.github.com/anonymous/68256e2c1ce8221414bd906886c381e8/raw/f4ca9e28bfbb019b2d4161d03c2268ae07c6b856/style.css and this is rawgit url: https://cdn.rawgit.com/anonymous/68256e2c1ce8221414bd906886c381e8/raw/dc7dde402451687bf4eaaf1ccb91e7be427b6076/style.css 

If it's supposed to not work for anon gist it'd be good if the rawgit warned you or something.

**Comment by theel0ja** [comment]
See this: https://twitter.com/rawgit/status/785156773401329665

**Comment by rpgdev** [comment]
@theel0ja thanks. You should put that up on the FAQ/landing page @rgrove @carpeliam @kitcambridge @holic

**Comment by desyncr** [comment]
Was asked [before](https://github.com/rgrove/rawgit/issues/132). Should be up in the wiki or `README.md`. Basically CC [this comment](https://github.com/rgrove/rawgit/issues/132#issuecomment-252683386).

**Comment by rgrove** [comment]
[Done](https://github.com/rgrove/rawgit/wiki/Frequently-Asked-Questions#why-do-anonymous-gist-urls-return-403-errors).
