### ISSUE TITLE
Can I delete files from cdn.rawgit.com?  

### ISSUE THREAD

**Issue by oshihirii** [rgrove/rawgit#141]
Hello,

I've been reading the FAQ:

https://github.com/rgrove/rawgit/blob/master/FAQ.md

I'm wondering if it is possible to delete files from a secret gist, for example, that are cached on:

cdn.rawgit.com

If I deleted the gist, would the cached file no longer exist?

Or is there some other way to delete the cached file?

Thank You.  

**Edit:**  Here is a link to purging from StackPath, it doesn't directly relate to cdn.rawgit.com, but hopefully shows it might be possible?  

https://support.stackpath.com/hc/en-us/articles/222954088-Purging-the-Cache-for-the-StackPath-CDN

**Edit:**  If the above is not possible, perhaps the service below would achieve the desired behaviour of not caching a file for ever?  It seems it only caches for 2 hours, does that mean if the github file is deleted then the file in the CDN would also no longer be there?  

https://gitcdn.xyz/

**Comment by rgrove** [comment]
The RawGit CDN caches non-master branch URLs (including secret gists) indefinitely once they're requested at least two times. There is no way for users to manually remove specific URLs from the cache.

In theory, a popular URL could remain in the CDN cache for years even after the source URL is deleted. However, if the URL receives no requests, then it will probably fall out of the CDN cache within a matter of days (if not sooner).

Complicating this is the fact that there are dozens of globally distributed CDN nodes and each node maintains its own cache. So if, for example, a URL frequently receives requests from users in Germany but rarely or never from elsewhere in the world, that URL's content would likely remain in the cache of the CDN node(s) in Frankfurt, Germany, but would not be cached by other nodes.

Secret gists, whether served by GitHub or by RawGit, are only as secret as the URL itself, so I don't recommend using secret gists for important secrets.

**Comment by oshihirii** [comment]
I really appreciate your answer.  Would you mind commenting on my second edit?  Thank you again.

**Comment by rgrove** [comment]
> Here is a link to purging from StackPath, it doesn't directly relate to cdn.rawgit.com, but hopefully shows it might be possible?

It is possible for _me_ to manually purge files from the CDN (and I have done this from time to time when people have asked me to), but I don't have any plans to expose this functionality publicly. The main reason is that it would be difficult to prevent abuse.

> If the above is not possible, perhaps the service below would achieve the desired behaviour of not caching a file for ever? It seems it only caches for 2 hours, does that mean if the github file is deleted then the file in the CDN would also no longer be there?
>
> https://gitcdn.xyz/

I'm not familiar with gitcdn.xyz, but it appears to be a fork of RawGit with different caching behavior, so if that's more in line with what you're looking for, then certainly feel free to use it. If you have questions about that service, you would need to ask its maintainer.

I may consider reducing RawGit's CDN TTL in the future, but for now one of the main benefits of the high TTL is that it significantly reduces load on RawGit's origin server by ensuring that very popular files (some of which get hundreds of gigabytes of traffic per month) are always served entirely from the CDN.

**Comment by oralee123** [comment]
I have to ask for something, if someone send me a link of rawgit, and my phone turnes off. Then what happend, did the person Gets everything, my pictures, my passwords or what?

**Comment by rgrove** [comment]
@oralee123 It sounds like someone may have sent you a malicious link that crashed your phone. Your data is probably fine, but please send me the link in question so I can remove it from RawGit and prevent this from happening to other people. You can email it to me at security@rawgit.com.
