### ISSUE TITLE
Verificar 

### ISSUE THREAD

**Issue by marcosjara** [rgrove/rawgit#143]
Ingles:
Dear rawgit,

Some malicious users of your service are using your service, (https://rawgit.com/) to provide malicious code,

They have invaded my server and I have found by the log, which is called an SH, which executes service tasks that slow my server, because it consumes memory

I request to inform the user and to verify, if they have any policy of use of the site, since I am complaining in the corresponding sites to cut and invalidate, besides informing the legal authorities about the damage caused to my server and service

SH Shell malicious script to which it is invoked:

Https://raw.githubusercontent.com/dirDirlsLs/catcheye/master/4.sh
Dear rawgit,

Some malicious users of your service are using your service, (https://rawgit.com/) to provide malicious code,

They have invaded my server and I have found by the log, which is called an SH, which executes service tasks that slow my server, because it consumes memory

I request to inform the user and to verify, if they have any policy of use of the site, since I am complaining in the corresponding sites to cut and invalidate, besides informing the legal authorities about the damage caused to my server and service

SH Shell malicious script to which it is invoked:

Https://raw.githubusercontent.com/dirDirlsLs/catcheye/master/4.sh

------
Español
Estimados rawgit,

Algun usuario mal intencionado de su servicio está utilizando el servicio de ustedes, (https://rawgit.com/) para disponibilizar código malicioso, 

Han invadido mi servidor y he encontrado por el log, que se llama a un SH, que ejecuta tareas de servicio que dejan lento mi servidor, por que consume memoria 

Solicito informar al usuario y verificar, si tienen alguna politica de uso del sitio, ya que estoy reclamando en los sitios correspondiente para cortar e invalidar, además de informar a las autoridades legales sobre el daño causado a mi servidor y servicio

SH Shell script malicioso al cual se invoca:

https://raw.githubusercontent.com/dirDirlsLs/catcheye/master/4.sh

---

**Comment by neoascetic** [comment]
Hm, those script kiddies could download the shell file directly from github as well, so there is almost nothing @rgrove can do against.

**Comment by rgrove** [comment]
@marcosjara: I've banned the GitHub user "dirDirlsLs" from RawGit. However, the malicious script is hosted on [GitHub](https://github.com/dirDirlsLs/catcheye/), which I don't control. Please report this to GitHub as well so that they can take action on their end.
