### ISSUE TITLE
New extension blacklist breaks CORS-sensitive image loading

### ISSUE THREAD

**Issue by chriswa** [rgrove/rawgit#144]
For example, loading an image to use as a texture in WebGL was working before https://github.com/rgrove/rawgit/commit/32c78accd7b78698b031c8b4ba23b24e2981482b , but with the new blacklist redirects, Chrome throws an error:

three.js:19351 DOMException: Failed to execute 'texImage2D' on 'WebGLRenderingContext': The cross-origin image at https://raw.githubusercontent.com/...png may not be loaded.

**Comment by rgrove** [comment]
Sorry for breaking this without warning; I forgot about this use case.

Unfortunately the amount of image traffic that was being unnecessarily proxied via RawGit was beginning to negatively affect RawGit's ability to serve non-image requests.

The good news is that GitHub already serves images from `raw.githubusercontent.com` with the correct `Content-Type` header and with `Access-Control-Allow-Origin: *`, so you should be able to fix this on your end by changing your `*.rawgit.com` URLs to `raw.githubusercontent.com`.

**Comment by chriswa** [comment]
Thanks! For reference, I just needed to set a crossOrigin property on my image to get my project working again. :)

And thanks for this excellent service!

**Comment by rgrove** [comment]
Awesome! Thanks for sharing those extra details.
