### ISSUE TITLE
http vs https connections

### ISSUE THREAD

**Issue by durack1** [rgrove/rawgit#145]
I'm currently using a http://rawgit.com URL to display some html pages stored in a github repo, which works a treat (thanks!).

Just wondering what the http vs https policy for rawgit will be going forward, as I am sourcing some externally hosted css etc and have hit some cert trickiness with the http vs https referencing in the past.. This can be browser specific, with Chrome the biggest complainer thus far

**Comment by rgrove** [comment]
I'm not sure exactly what kind of reassurance you're looking for, but RawGit will always support HTTPS, will always use strong, widely supported cipher suites, and will always use a certificate signed by an authority that's trusted by recent versions of all major browsers.

**Comment by durack1** [comment]
@rgrove thanks for replying.. My query was actually related to maintaining http connections to rawgit, rather than getting redirected to https connections as is the case with some of the other services raw.githubusercontent.com for e.g.

**Comment by rgrove** [comment]
I don't currently have plans to eliminate HTTP support since doing so has caused problems for people in the past, but I strongly encourage you to use HTTPS. The web as a whole is moving away from HTTP.

**Comment by durack1** [comment]
Thanks @rgrove, I am aware that eventually I will need to use https.. But was curious as to the plans, if you have no intention to force https for the immediate future that is good information for me. Thanks!
