### ISSUE TITLE
Avatar support

### ISSUE THREAD

**Issue by f3l1x** [rgrove/rawgit#146]
Hi. Thank you for great job on rawgit.

Do you plan to support avatar caching?

**Comment by rgrove** [comment]
What do you mean by "avatar caching"?

**Comment by f3l1x** [comment]
I'm not really sure but I was wondering about something like that.

```
https://cdn.rawgit.com/{vendor}.png
```

What do you think?

**Comment by rgrove** [comment]
Sorry, I'm still not sure what you're asking for.
