### ISSUE TITLE
Add shortener service 

### ISSUE THREAD

**Issue by kpym** [rgrove/rawgit#147]
Is it possible to add a "shortener" service for the CDN version ?

What I mean by this is to add a link like `https://cdn.rawgit.com/5h0rT` in addition to the standard `https://cdn.rawgit.com/user/xxxxxxxxxxxxxxxxxxx/raw/xxxxxxxxxxxxxxxxxxxxxxxxx/filename.ext`.

Thanks for your work !

**Comment by rgrove** [comment]
Thanks for the suggestion.

I think URL shortening is something best left to existing services like Bit.ly. Those services can already shorten RawGit URLs, so I'm not sure there's a need for RawGit to provide its own short URLs.

**Comment by kpym** [comment]
I know there are plenty of shorteners, but the difference is the speed (this is the main reason for the existence of CDN by the way) : when you use a shortener service you add a supplementary http request (plus the resolve time). If the shortener service is provided by the CDN, there is almost no supplementary delay. 
But I understand that you don't want to complexify your service.

**Comment by rgrove** [comment]
I did seriously consider this. Here's my reasoning:

The primary value of a shortener is in reducing a long or unattractive URL to a shorter, more readable URL that's better suited for displaying to a user, being shared, or being written down. In this scenario, the end result is that a human will click on, paste, or type the URL into a browser. The slight performance penalty incurred by a shortener redirect is not likely to be noticeable by most humans, and is a small price to pay for the ease of transcription and sharing provided by a shorter URL.

But there's no value in using shortened URLs for assets that will be loaded by a browser without manual human entry, which is the primary use case for RawGit URLs. Browsers don't care whether a JS URL is 100 characters long or 15 characters long. The most important thing in this scenario is that the URL _load_ quickly, not that it be short or readable. Any shortening service, even one provided by RawGit, would add a lookup delay to the process of serving an asset, and in this scenario any delay, no matter how brief, is a large price to pay given that no actual value is being provided.

This is why I don't see URL shortening as a service that RawGit needs to provide.

**Comment by kpym** [comment]
Thanks to taking the time to consider the question and to write your well argued answer. Finally I agree with you.
