### ISSUE TITLE
source URL

### ISSUE THREAD

**Issue by morandd** [rgrove/rawgit#150]
Stupid question, but could you clarify in the FAQ which kind of source URL we should provide.

Should it be the github.com url, or the raw.githubusercontent.com url?

e.g
https://github.com/flozz/StackBlur/blob/1.4.0/dist/stackblur.min.js
or
https://raw.githubusercontent.com/flozz/StackBlur/1.4.0/dist/stackblur.min.js

thanks

**Comment by desyncr** [comment]
It should be raw but it manages to retrieve raw if github url is given. See https://github.com/rgrove/rawgit/commit/c378c0103a334a9a65dc9553c50f65603892ef7e

**Comment by rgrove** [comment]
Yep, either one will work fine.

I think this is one of those things it's easy to try for yourself, so I'm not sure a FAQ entry is needed. If this question comes up again, I'll consider adding one.
