### ISSUE TITLE
Allow subdomains to specify the Github user to provide isolated origins

### ISSUE THREAD

**Issue by fabio-looker** [rgrove/rawgit#152]
Currently, if I have an HTML page that uses localStorage, any other HTML page uploaded to Github could access data that a user enters on my HTML page.

If we simply allowed URLs of the form http(s)://user.rawgit.com/repo/branch/* (which could be in addition to the current routing scheme), then each user could have their own isolated origin.

I can work on the code and submit a pull request, if you like the idea and would be able to add the right wildcard DNS entry & wildcard SSL.

**Comment by rgrove** [comment]
Thanks for the suggestion. I agree that isolated per-user origins would be a neat feature, but there are a number of reasons why I'm not likely to add this to RawGit:

-   Wildcard SSL certs are expensive.

-   Cloudflare, which rawgit.com (but not the CDN) uses for DDoS protection, [only supports proxying of wildcard DNS entries for Enterprise-level customers](https://support.cloudflare.com/hc/en-us/articles/200168826-Does-Cloudflare-support-wildcard-DNS-entries-), which is expensive.

-   We would have to support both `user.rawgit.com` and `user.cdn.rawgit.com`, which increases the complexity of this feature at all layers of RawGit's stack.

But perhaps the biggest reason is that RawGit isn't intended to be a static _site_ hosting platform. RawGit is a static _asset_ proxy that's intended to make development and prototyping easier. 

There are much better solutions for hosting static websites. Some of them, like GitHub Pages, are even free and tightly integrated with GitHub, so I don't see this as an area where RawGit is needed.

**Comment by fabio-looker** [comment]
And now I know about GitHub Pages! Thanks :)
