### ISSUE TITLE
Pasting Github file to rawgit doesn't work please help

### ISSUE THREAD

**Issue by TrappedNetworks** [rgrove/rawgit#153]
I've been trying for the past hour to get rawgit to work, I've created my github file several different times and nothing is working. I've followed tutorials properly on how to create my file so there's no issue there, I'm fairly new to this so any help would be greatly appreciated.
https://github.com/TrappedNetworks/loadingscreenwork
This is the file that I'm trying to get to work.

**Comment by rgrove** [comment]
RawGit URLs must be individual files.

The URL https://github.com/TrappedNetworks/loadingscreenwork points to a directory, not a file. 

If you're trying to serve `index.html` via RawGit, then you should paste in the URL https://github.com/TrappedNetworks/loadingscreenwork/blob/master/index.html, which maps to the RawGit URL https://rawgit.com/TrappedNetworks/loadingscreenwork/master/index.html.

**Comment by TrappedNetworks** [comment]
I meant to post that, i got the incorrect link. When I put inhttps://github.com/TrappedNetworks/loadingscreenwork/blob/master/index.html it stays grey.

**Comment by TrappedNetworks** [comment]
but thanks for the rawgit url it helps alot, but I would still appreciate a fix

**Comment by TrappedNetworks** [comment]
nevermind, it was an adblocker that was disabling the process. thanks for the support
