### ISSUE TITLE
RawGit not rendering markdown files correctly?

### ISSUE THREAD

**Issue by hlwarriner** [rgrove/rawgit#154]
I'm pretty new to markdown and completely new to GitHub and RawGit, so sorry if this is a silly question. But, should RawGit be able to render .md files from GitHub as markdown files?

For example, https://cdn.rawgit.com/hlwarriner/resume/e69d5654/holden-warriner-resume.md is just displaying the contents of the .md file as plain text.

Thanks!

**Comment by rgrove** [comment]
Sorry, RawGit doesn't render Markdown.

You may want to look into [GitHub Pages](https://pages.github.com/), which allows you to [use the Jekyll static site generator](https://help.github.com/articles/about-github-pages-and-jekyll/) to render Markdown content that's hosted in a GitHub repo. In that scenario, GitHub Pages will serve (and render) your Markdown content and you won't need RawGit.
