### ISSUE TITLE
Privacy Badger blocks rawgit.com

### ISSUE THREAD

**Issue by mlinksva** [rgrove/rawgit#163]
I'm not sure why, but dropping an issue here as it hasn't been mentioned in this repo AFAICT but has various other places https://github.com/search?utf8=%E2%9C%93&q=rawgit+%22privacy+badger%22&type=Issues

I noticed when a [site](https://www.talater.com/open-source-templates/#/) that uses rawgit.com was semi-broken until I disabled Privacy Badger blocking rawgit.com for that site.

This may be not rawgit.com's problem, in which case I apologize for wasting your time!

**Comment by rgrove** [comment]
Thanks for letting me know. I don't think there's anything I can do about this from RawGit's end. It looks like someone did report this on the Privacy Badger repo, but they don't seem to have done anything about it: https://github.com/EFForg/privacybadger/issues/1598

The RawGit CDN doesn't do any tracking beyond basic Nginx request logs, but it's certainly possible that there are people who use RawGit to serve their own tracking JS. If anyone is aware of specific RawGit URLs that are being used for anything malicious or invasive, please let me know!

**Comment by ghostwords** [comment]
@mlinksva Could you run the following JavaScript in your Privacy Badger's background page and let me know what it prints out? For more information and instructions for getting to the page, please see https://gist.github.com/anonymous/8aebb8e48a1ce3c256b21dcfe37af84b.
```javascript
(function () {
  const STR = "rawgit.com";
  console.log("**** ACTION_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('action_map').getItemClones(), (obj, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(obj, null, 2));
  });
  console.log("**** SNITCH_MAP for", STR);
  _.each(badger.storage.getBadgerStorageObject('snitch_map').getItemClones(), (sites, domain) => {
    if (domain.indexOf(STR) != -1) console.log(domain, JSON.stringify(sites, null, 2));
  });
}());
```

**Comment by mlinksva** [comment]
@ghostwords here's what I get (yes I looked and don't care that anyone knows I visited the 3 sites it says):

```
**** ACTION_MAP for rawgit.com 
cdn.rawgit.com {
  "userAction": "",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1509926834060
} 
rawgit.com {
  "userAction": "user_cookieblock",
  "dnt": false,
  "heuristicAction": "block",
  "nextUpdateTime": 1508483967465
} 
**** SNITCH_MAP for rawgit.com 
rawgit.com [
  "modernfarmer.com",
  "laboratorium.net",
  "techdirt.com"
]
```
