### ISSUE TITLE
rawgit content type problem

### ISSUE THREAD

**Issue by GrosSacASac** [rgrove/rawgit#164]
https://raw.githubusercontent.com/GrosSacASac/DOM99/master/examples/templates3.html

i get it as text

https://cdn.rawgit.com/GrosSacASac/DOM99/master/documentation/documentation.html#about

however is fine,

original:

https://github.com/GrosSacASac/DOM99

**Comment by rgrove** [comment]
raw.githubusercontent.com is GitHub, not RawGit.
