### ISSUE TITLE
Is there any API one can use to get a link from given GitHub raw URL from CLI?

### ISSUE THREAD

**Issue by nikitavoloboev** [rgrove/rawgit#165]
Thank you a lot for this wonderful tool.

**Comment by rgrove** [comment]
RawGit doesn't provide an API for this and I'm not aware of any third party APIs, but the source code for the URL formatter on the RawGit homepage (which you could use to do this) is here: https://github.com/rgrove/rawgit/blob/master/public/js/url-formatter.js
