### ISSUE TITLE
Production links no longer include hashes

### ISSUE THREAD

**Issue by wlandau** [rgrove/rawgit#173]
The production links seem to work, but the URLs no longer include hashes (e.g. https://cdn.rawgit.com/ropensci/drake/ddefa828/images/reg2-small-legend.html). Is this the intended behavior now?

![capture](https://user-images.githubusercontent.com/1580860/36801881-404331dc-1c81-11e8-8c9e-327666fd66a5.PNG)

**Comment by rgrove** [comment]
If the GitHub API request to fetch the commit hash doesn't succeed, the URL formatter falls back to the branch used in the input URL.

You might be rate-limited, or the GitHub API could be failing for some other reason. It's working for me though:

![1802288aprx](https://user-images.githubusercontent.com/1465/36803038-5c5b5f7c-1c6b-11e8-9ab1-f5cf4beb13d0.jpg)
