### ISSUE TITLE
WebAssembly mimetype support (wasm)

### ISSUE THREAD

**Issue by ImagicTheCat** [rgrove/rawgit#174]
`.wasm application/wasm`
https://github.com/WebAssembly/design/blob/master/Web.md

WebAssembly specification seems to require this mimetype to load `wasm` files, is it possible to support it with rawgit ?

**Comment by rgrove** [comment]
Should work now!

**Comment by ImagicTheCat** [comment]
Seems ok using wget, nice, thank you.
