### ISSUE TITLE
Add privacy policy for GDPR compliance

### ISSUE THREAD

**Issue by Zodiac1978** [rgrove/rawgit#182]
In the EU we need to document which third-party resources are loaded on our websites and if personal data is protected. As the data is send to StackPath, I could link their privacy policy (https://www.stackpath.com/privacy-statement/) - but I need to know if rawgit.com itself saves any personal data. Could you please add a privacy policy I can link on my websites privacy policy?

**Comment by rgrove** [comment]
I'm unlikely to have time to work on this soon, but if someone with experience writing GDPR-compliant privacy policies would like to take a crack at it, please feel free.

Quick summary of the data RawGit collects:

-   IP addresses and user agent strings of HTTP clients that make requests to rawgit.com or cdn.rawgit.com are logged by Nginx and stored for up to 14 days. These logs are used to debug site issues and to detect abuse.

-   RawGit's origin server is hosted on DigitalOcean. This is where Nginx logs are stored. DigitalOcean's privacy policy is [here](https://www.digitalocean.com/legal/privacy/).

-   Requests to cdn.rawgit.com pass through MaxCDN, which is owned by StackPath. MaxCDN has a privacy policy [here](https://www.maxcdn.com/legal/#pp). StackPath has a privacy policy [here](https://www.stackpath.com/privacy-statement/). I honestly don't know whether one or both policies apply to MaxCDN traffic.

-   Requests to rawgit.com pass through Cloudflare, which has a privacy policy [here](https://www.cloudflare.com/privacypolicy/).

-   Requests for uncached files on rawgit.com and cdn.rawgit.com are ultimately passed to GitHub, which has a privacy policy [here](https://help.github.com/articles/github-privacy-statement/).

-   The rawgit.com homepage uses Google Analytics to gather aggregate data about site usage.
