### ISSUE TITLE
How to block rawgit.com to access my website ?

### ISSUE THREAD

**Issue by crossing1** [rgrove/rawgit#185]
Hello,

I think some hacker injected some script that is using rawgit.com. Recently my website is connected for some reason with rawgit.com, I noticed my website is slower lately and then I sow the bottom browser message "Transferring data from rawgit.com" or "Read rawgit.com" right when my website is slower/ frozen.  I have never used rawgit.com so I'm pretty sure something is wrong.  I would like to totally block my website from getting data from rawgit.com, cdn.rawgit.com, can you tell me the full hataccess content to achieve that ?   Thank you.

**Comment by crossing1** [comment]
I have tried on 3 browsers with the same result.

**Comment by neoascetic** [comment]
Well, any 3rd party script (gallery plugin, whatever) can load something from rawgit.

**Comment by crossing1** [comment]
So you're saying that the chances are very slim that someone is actually attacking my website.

**Comment by neoascetic** [comment]
I am saying that it is better to check 3rd party stuff on your website first. In devtools you can see which script initiated the request to rawgit.

**Comment by rgrove** [comment]
@crossing1 If you let me know the URL of your website, I can find and ban the offending script.

**Comment by nektro** [comment]
@crossing1 also look into [Subresource Integrity](https://www.srihash.org/) and [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) and make sure to let rgrove which script is causing your issue, as it may be causing others trouble as well.
