### ISSUE TITLE
Enable HTTP/2 on rawgit and cdn.rawgit

### ISSUE THREAD

**Issue by nektro** [rgrove/rawgit#186]

**Comment by rgrove** [comment]
HTTP/2 has been enabled on rawgit.com and cdn.rawgit.com for years, so I'm a little puzzled by this request. If you're not able to establish HTTP/2 connections to RawGit, please add more details and we can try to figure out what's happening.

**Comment by nektro** [comment]
`rawgit.com` comes up as `spdy` instead of `h2`

![image](https://user-images.githubusercontent.com/5464072/43617082-ec891002-968d-11e8-8be2-1a107f80bec9.png)
![image](https://user-images.githubusercontent.com/5464072/43617099-06e9ad30-968e-11e8-9b05-9538ed530fec.png)

**Comment by rgrove** [comment]
This may be [a bug in the Chrome dev tools](https://groups.google.com/a/chromium.org/forum/#!topic/chromium-discuss/PYCV9EuYers) that causes it to display the protocol as `spdy` instead of `h2`.

**Comment by nektro** [comment]
It's still not fix in v68 but Firefox is reporting the protocol correctly, so it seems it is Chrome's issue here.
