### ISSUE TITLE
PNG Images being sent with Content-Type: text/plain

### ISSUE THREAD

**Issue by shellscape** [rgrove/rawgit#187]
Not sure what's going on there, but a PNG image is being sent with a Content-Type of `text/plain`. See curl output below:

```console
→ curl -I https://cdn.rawgit.com/shellscape/solsoul.github.io/bfe46582/assets/external/signature.png
HTTP/2 301 
date: Mon, 20 Aug 2018 15:10:42 GMT
content-type: text/plain; charset=utf-8
content-length: 135
location: https://raw.githubusercontent.com/shellscape/solsoul.github.io/bfe46582/assets/external/signature.png
x-content-type-options: nosniff
x-robots-tag: none
access-control-allow-origin: *
cache-control: max-age=2592000
vary: Accept
rawgit-cache-status: MISS
server: NetDNA-cache/2.2
strict-transport-security: max-age=31536000; preload
x-cache: MISS
```

**Comment by neoascetic** [comment]
That's because it is being redirected. It's `301`.

**Comment by shellscape** [comment]
@neoascetic yes, I can see that. That rawgit URI is what rawgit provided me when I pasted the full path to the file. So then the question becomes - why is rawgit redirecting to the file? 

@rgrove premature close there my dude.

**Comment by rgrove** [comment]
@shellscape Requests for .png files are redirected to GitHub because GitHub already serves them with the proper `Content-Type` headers. There's no need for RawGit to proxy these requests. If you don't like the redirect, use the GitHub URL rather than the RawGit URL.

**Comment by shellscape** [comment]
@rgrove that's the info I was looking for. Thanks.
