### ISSUE TITLE
https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js file missing content

### ISSUE THREAD

**Issue by ffrhtt** [rgrove/rawgit#198]
v5.1.3/build/ol.js file content missing

This file content has the error. Go to the last line, you can see n.prototype.getId=functio .

I have used this library, and I have to change all my application. This is difficult for me. Because I used in IOS, Android, WEB application.
![capture](https://user-images.githubusercontent.com/46048610/50345185-31514900-053f-11e9-8e02-be36c52270e7.PNG)

**Comment by ffrhtt** [comment]
@rgrove  I reads: RawGit has reached the end of its useful life. I understand this issue, but My all application using https://cdn.rawgit.com/openlayers/openlayers.github.io/master/en/v5.1.3/build/ol.js file, I need to more time for the update from everywhere. Can you fix this issue temporary?

**Comment by rgrove** [comment]
RawGit is still serving that file. If the content of the file is not what you expect, it may have changed in the repository. This isn’t something RawGit has control over.
