### ISSUE TITLE
Please "terminate" support, don't "sunset" it

### ISSUE THREAD

**Issue by earthbound19** [rgrove/rawgit#199]
http://earthbound.io/no-no-no-no-no/#sunset-instead-of-terminate-service

**Comment by rgrove** [comment]
RawGit has not been terminated.

It is in a sunset phase. A sunset starts, lasts for some amount of time during which everyone reacts to it and prepares for the disappearance of the sun, and then eventually the sun dips below the horizon and is no longer visible. At that point, RawGit will be terminated.

By the way, opening pedantic issues for personal pet peeves like this is a jerk move. It wastes everyone's time and doesn't make anything better. Please don't do it. Especially don't do it when you're wrong.
