### ISSUE TITLE
'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

### ISSUE THREAD

**Issue by AbdullahAlhazzani** [rgrove/rawgit#205]
Access to font at '[URL]' from origin 'null' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed.

**Comment by kotx** [comment]
Why is this closed? Did you find a solution?

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/194372666-5dd0b528-34ad-4a3d-83c2-2914a788da75.png)
The problems seems to be caused by dumplicated headers, yet I am not finding the author answer why there are mutiple ones,
