### ISSUE TITLE
CORS error: (Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, *’)

### ISSUE THREAD

**Issue by M0hammedImran** [rgrove/rawgit#207]
I get this when ever I try to use it.
`(Reason: CORS header ‘Access-Control-Allow-Origin’ does not match ‘*, *’)`

This is the URL: `https://cdn.githubraw.com/M0hammedImran/test-deploy/main/protoezy.bundled.js`

**Comment by neoascetic** [comment]
This is time to block issues I guess

**Comment by Mister-Hope** [comment]
@rgrove  Why is this invalid?

![image](https://user-images.githubusercontent.com/33315834/194372333-1b6a8fa7-f639-4648-bc0a-435aeaa5581c.png)

A resource is not supposed to return a dumplicate header?

**Comment by jimaek** [comment]
githubraw.com is not rawgit.com


Wrong repo

**Comment by Mister-Hope** [comment]
![image](https://user-images.githubusercontent.com/33315834/194374282-20fc679d-1cfa-4e22-ae3f-80e557fd8c05.png)


So you are saying that githubraw.com is not related to this project? I do saw rawgit say it's down at https://rawgit.com/

If so, and githubraw.com reference this repo by its own, maybe maintainers should add some warnings in these links saying that this project is down and no longer get maintainance, and githubraw is not related to this project.

**Comment by jimaek** [comment]
>So you are saying that githubraw.com is not related to this project? I do saw rawgit say it's down at https://rawgit.com/

exactly. Just because they say rawgit it doesnt mean the rawgit owners have nothing to do with that project. Its unrelated and nobody in this repo can help.

If you want a better CDN consider using jsDelivr https://cdn.jsdelivr.net/gh/vuepress-theme-hope/vuepress-theme-hope/packages/theme/templates/giscus/light.css

**Comment by jimaek** [comment]
The about in Github has "No longer actively developed." and the main website says "RawGit has reached the end of its useful life".

**Comment by Mister-Hope** [comment]
TBH, I really missed the first one because it's on the right side with PC, but I catch the second one though.

I think adding this at the start of the README will be better.

**Comment by rgrove** [comment]
a191bd9bc11aff7fabf05aea34eab3f8e64bc307
