### ISSUE TITLE
Error or Bug

### ISSUE THREAD

**Issue by Jetrom17** [rgrove/rawgit#210]
I tested with CDN and Githubraw. I updated my "raw" on Github. In a few minutes the tool with CDN was updated and Githubraw has not been updated. Since on its official page, it says that the resource used with CDN does not reflect with GitHub repository.

**Comment by rgrove** [comment]
githubraw.com is not affiliated with RawGit. It uses the RawGit source code and links to this repo, but I have no idea who runs it.

Whoever it is, I wish they would remove my name and the links to this repo so that people would stop thinking I run the thing.

**Comment by Jetrom17** [comment]
> githubraw.com is not affiliated with RawGit. It uses the RawGit source code and links to this repo, but I have no idea who runs it.
> 
> Whoever it is, I wish they would remove my name and the links to this repo so that people would stop thinking I run the thing.

Sorry for the inconvenience. I suggest you explain this on your website to avoid future confusion.

**Comment by rgrove** [comment]
> I suggest you explain this on your website to avoid future confusion.

Please see the warning at the top of the readme: https://github.com/rgrove/rawgit#readme

**Comment by Jetrom17** [comment]
> > I suggest you explain this on your website to avoid future confusion.
> 
> Please see the warning at the top of the readme: https://github.com/rgrove/rawgit#readme

No no, on your site.
