### ISSUE TITLE
Add support for bitbucket

### ISSUE THREAD

**Issue by malik022** [rgrove/rawgit#49]
Can we get added support for Bit Bucket?

**Comment by ckpoon** [comment]
Can we also support Gitlab? Or a generic solution for all these kind of platform
It is a self-hosted Github-like platform. 

Sample Raw File through API request,
http://stackoverflow.com/questions/24207644/open-a-file-directly-from-a-gitlab-private-repository

**Comment by rgrove** [comment]
@ckpoon: This issue is about Bitbucket. Feel free to open a new issue for Gitlab, but please don't hijack this one. Thanks!

**Comment by lightblade** [comment]
:+1: This one

**Comment by michaelsoriano** [comment]
+1 for Bitbucket

**Comment by soham2008xyz** [comment]
:+1:

**Comment by joelself** [comment]
Come take a look at raweverything @ https://raweverything.dislocal.com. It supports bitbucket and a number of other repositories and file hosts. The source was forked from this project. You can find it here: https://github.com/joelself/raweverything

**Comment by neoascetic** [comment]
Oh, well, [bb.githack.com](http://bb.githack.com) also works...

**Comment by rgrove** [comment]
Thanks folks! Since there are now multiple options to choose from for Bitbucket support and since I'd prefer not to increase the scope of the RawGit service for now, I'll go ahead and close this issue.

**Comment by Jolg42** [comment]
https://raw.githack.com/ is a good alternative!
