### ISSUE TITLE
make source host configurable

### ISSUE THREAD

**Issue by eins78** [rgrove/rawgit#52]
It seems the "source host" is hard-coded:
https://github.com/rgrove/rawgit/search?utf8=%E2%9C%93&q=githubusercontent

If it could be configured, it would ease (internal) deployments for other hosts than "normal" github, for example Github Enterprise.

**Comment by rgrove** [comment]
Thanks for the suggestion! I'd merge a PR that implements this, or if nobody gets around to it before I do, I'll implement this when I have some free time.

**Comment by eins78** [comment]
> if nobody gets around to it before I do, I'll implement this when I have some free time

Cool. I might need it myself soonish, would take a stab at it then.

**Comment by rgrove** [comment]
Fixed by f58f556f.
