### ISSUE TITLE
Getting 200 OK for cached resource

### ISSUE THREAD

**Issue by AndreasPizsa** [rgrove/rawgit#54]
Hi,
thanks for this wonderful service!

I'm currently getting `200 OK` responses on all my requests, so caching on the client is effectively off. Do you have any ideas why this might be?

eg URL `https://cdn.rawgit.com/kriskowal/q/3f62d467cb55efe4e0f53fa880239ab5057990e8/q.js`

### Request Headers
```
:host:cdn.rawgit.com
:method:GET
:path:/kriskowal/q/3f62d467cb55efe4e0f53fa880239ab5057990e8/q.js
:scheme:https
:version:HTTP/1.1
accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
accept-encoding:gzip, deflate, sdch
accept-language:en-US,en;q=0.8,de;q=0.6,fr;q=0.4
cache-control:max-age=0
cookie:_ga=GA1.2.547487526.1413531650
user-agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.50 Safari/537.36
```

### Response Headers
```
access-control-allow-origin:*
cache-control:max-age=315569000
content-encoding:gzip
content-type:application/javascript; charset=utf-8
date:Mon, 23 Mar 2015 16:03:42 GMT
rawgit-cache-status:HIT
server:NetDNA-cache/2.2
status:200 OK
vary:Accept-Encoding
version:HTTP/1.1
x-cache:HIT
x-content-type-options:nosniff
x-robots-tag:none
```

Thank you!

A.

**Comment by rgrove** [comment]
The request includes a `cache-control:max-age=0` header, which indicates that the client is intentionally disabling caching. The CDN is responding with a correct `cache-control` header, so this looks like purely a client-side issue.

Are you sure you didn't disable the cache in Chrome DevTools or something and forget about it? I do that all the time.
