### ISSUE TITLE
shortlinks

### ISSUE THREAD

**Issue by branderxero** [rgrove/rawgit#56]
your service is great.  but urls like: 

`https://cdn.rawgit.com/branderxero/44209619ba485e32d7b3/raw/be86b2237efd035b068652b855fc79cef6161cf5/vim-colors.html`

are impossible to remember. i'd be wonderful if you offered a shortened url option. e.g. 

`https://x.rawgit.com/c1v`

**Comment by neoascetic** [comment]
You may use any third-party service to generate shortlink. Why this need to be done in rawgit?
Here the example: http://bit.ly/1EGmOGg

**Comment by rgrove** [comment]
Agreed. I don't think RawGit needs to provide this. :)
