### ISSUE TITLE
URLs with "%20" are converted to "%2520" at http://rawgit.com/ , lead to 404

### ISSUE THREAD

**Issue by Vdragon** [rgrove/rawgit#58]
Hi, I tried to convert https://github.com/Vdragon/Vdragon_s_License_Templates/blob/217eea4d6e13a5f72eddf1f1a3b22dbdee9e9639/Creative%20Commons/CC%20BY-SA/Resources/Creative%20Commons%20CC-BY-SA%20logo.svg to *rawgit.com URLs but found all %20s been coverted to %2520s and wrong URLs generated.

**Comment by rgrove** [comment]
Should be better now. Thanks for the report!
