### ISSUE TITLE
PDF mimetype support

### ISSUE THREAD

**Issue by zbycz** [rgrove/rawgit#59]
Hi,

thanks for this ingenious service!  Can you please add support for PDF?
I think its very simple - just add some lines to `conf` folder, but it will be easier for you.
Correct mime type is `application/pdf`. Now I recieve redirect to raw.github.com which downloads with application/octet-stream.

Thanks
Pavel

**Comment by rgrove** [comment]
I'm curious why you'd want to request PDFs via rawgit.com as opposed to cdn.rawgit.com (which doesn't impose any file type limitations). Since rawgit.com is only for low-traffic demos and examples, how would PDF support be useful there?

**Comment by zbycz** [comment]
I want to link always current version of a document, thus I use
rawgit.com/user/repo/master/file.pdf - its linked from readme.md, so I cant
point to concrete commit.

**Comment by rgrove** [comment]
Fair enough. Please don't abuse this for anything that will get a lot of traffic though.

**Comment by zbycz** [comment]
I won't. But it'd be rather difficult to explain to other people. Until
yesterday I thought that rawgit.com is GitHub's own service, and was
surprised that it isn't :)

Btw, thanks for the fix.
