### ISSUE TITLE
404 error: possibly some characters in filename

### ISSUE THREAD

**Issue by Hubbitus** [rgrove/rawgit#60]
I want share test result in html: https://github.com/Hubbitus/tests/blob/0873d49144278680cd1ce4a6497adafdf6bb4979/bbcp/results/test-rsync-without-z%2Bc.2015-04-21_11:49:02.html

Rawgit generates me https://cdn.rawgit.com/Hubbitus/tests/0873d49144278680cd1ce4a6497adafdf6bb4979/bbcp/results/test-rsync-without-z%252Bc.2015-04-21_11:49:02.html URL which lead to 404 error.

Dev/testing: https://rawgit.com/Hubbitus/tests/0873d49144278680cd1ce4a6497adafdf6bb4979/bbcp/results/test-rsync-without-z%252Bc.2015-04-21_11:49:02.html also fail.

**Comment by rgrove** [comment]
Fixed. Thanks for the report!
