### ISSUE TITLE
Add support for private repositories

### ISSUE THREAD

**Issue by mitar** [rgrove/rawgit#62]
When I access a private raw file in GitHub, GitHub appends a token to the URL so that one can acess it:

```
https://raw.githubusercontent.com/...?token=...
```

When I open rawgit URL I get 404. :-(

It seems token is not used/passed on?

I would need this to be able to add SVG images to the README in a private repository.

**Comment by rgrove** [comment]
Sorry, private repos are intentionally not supported because I don't want peoples' tokens flowing through RawGit (or the CDN). That's too much scary responsibility!

Feel free to fork RawGit and run a private instance that adds that functionality though.

**Comment by mitar** [comment]
Oh. But you could just display a warning once somebody pastes in a link with a token? No? That this is insecure. And aren't tokens per-file anyway?

Hm, you could at least display an error in this case. And not strange 404.

**Comment by rgrove** [comment]
Good idea. I'll consider adding a special error.

**Comment by duttaditya18** [comment]
@rgrove Any plans for this?

**Comment by rgrove** [comment]
Still no plans to support private repos. Especially now, since people have recently been trying to use RawGit to distribute malware. The last thing I need is malware hosted in a private repo that I can't see.

**Comment by ErShakirAnsari** [comment]
Can we access a private repo's raw file using private access token in url?
