### ISSUE TITLE
Pasting this GitHub file URL (from raw.githubusercontent.com) doesn't seem to work

### ISSUE THREAD

**Issue by darkred** [rgrove/rawgit#65]
I've tried (in FF, IE, Chrome) to paste either of these URLs (from [here](https://github.com/pklauzinski/jscroll)) to https://rawgit.com/
`https://raw.githubusercontent.com/pklauzinski/jscroll/master/jquery.jscroll.js` or
`https://raw.githubusercontent.com/pklauzinski/jscroll/master/jquery.jscroll.min.js`
but the rawgit URLs for dev/testing and production are not generated.

Why is this happening?

**Comment by rgrove** [comment]
Seems to be working fine for me:

![1505085jbzn](https://cloud.githubusercontent.com/assets/1465/7541371/bfebf794-f569-11e4-92aa-722490e878e0.png)

You don't have JavaScript disabled or anything, do you? (Sorry, I have to ask.)

Also, when you click the following link, do you see a JS response?

https://cdn.rawgit.com/rgrove/rawgit/cdn-20150421/public/js/url-formatter.js

**Comment by rgrove** [comment]
Looks like one of the CDN edge nodes in France had a bad JS file cached, so if that happened to be the closest node to you, that would explain why the URL formatter wasn't working.

I've flushed the bad file out of the cache, so things should be better now. You may need to clear your browser cache as well. Let me know if you still have trouble after doing that. Thanks for reporting the issue!

**Comment by darkred** [comment]
No problem. Yes, of course Javascript is enabled.
Yes, it's now working.
Thanks for fixing this.
