### ISSUE TITLE
XSLT doesn't work

### ISSUE THREAD

**Issue by o11c** [rgrove/rawgit#68]
Pages that are client-transformed by an XML stylesheet don't work.

I suspect, but have not tested, that simply adding `.xslt` (and `.xsl`) to the whitelist so they're not served as text/plain might work.

Works: https://o11c.github.io/foo-test/foo-root.xml
Fails: https://rawgit.com/o11c/o11c.github.io/master/foo-test/foo-root.xml

**Comment by rgrove** [comment]
Added!

Sidenote: it looks like you're using RawGit to access a file that's already in a GitHub Pages repo, so you could also just use http://o11c.github.io/foo-test/foo-root.xml (though of course you're still welcome to use RawGit).

**Comment by o11c** [comment]
> Sidenote: it looks like you're using RawGit to access a file that's already in a GitHub Pages repo

That only works for the master branch of the main repo, not for other branches or forks.
