### ISSUE TITLE
rawgit.com shouldn't treat release URLs as if they're valid raw URLs

### ISSUE THREAD

**Issue by rgrove** [rgrove/rawgit#71]
The paste widget on rawgit.com thinks release URLs like https://github.com/migme/beachball/releases/download/v2.2.0/migme-beachball.min.js are valid raw URLs because they appear to follow the `/user/repo/branch/path` format. Oops.

**Comment by usmanatron** [comment]
Hi,
I'm working on fixing this and have a quick question about running the tests.  Essentially, I'm trying to run them on Windows and they don't appear to be working (for example, "npm test" throws an error).  Can I just confirm what you're developing from, just to make sure it isn't me missing something?

Thanks
Usman

PS: I have a prototype regex working; just want to test everything before sending a PR :-)

**Comment by rgrove** [comment]
@usmanatron Thanks for tackling this! I use OS X myself, and I don't test RawGit on Windows since it's not expected to run there, but the URL formatter isn't covered by the tests right now anyway.

**Comment by rgrove** [comment]
Fixed by #103. Thanks @usmanatron!
