### ISSUE TITLE
Is there a list of MIME types that you recognize?  Can this be edited?

### ISSUE THREAD

**Issue by markwilkinson** [rgrove/rawgit#74]
Hi!  

I'm serving OWL (ontology) files from Git, with the (typical) .owl extension.  These are in RDF-XML format.  They are being served as text/plain, rather than application/rdf+xml.  Is there a way to "force" rawgit to serve them with the correct Content-type header?

Cheers!

Mark

**Comment by rgrove** [comment]
@markwilkinson `.owl` files should now be served with an `application/rdf+xml` content-type. Enjoy!
