### ISSUE TITLE
404 error: After sertain commit

### ISSUE THREAD

**Issue by sdimkov** [rgrove/rawgit#75]
After I made this commit https://github.com/sdimkov/hubot-skype-web/commit/fa6e490be549691de499e7eade4823af9ed62bd5 all links to rawgit result in 404.

I believe something went wrong with the CDN cache but I can only guess.

Working link:
https://cdn.rawgit.com/sdimkov/hubot-skype-web/v0.9.3/doc/index.html

Non-working links:
https://cdn.rawgit.com/sdimkov/hubot-skype-web/v0.9.4/doc/index.html
https://cdn.rawgit.com/sdimkov/hubot-skype-web/fd2f67e3b06b78fccac9483dde5111e6b47b72ed/doc/index.html
https://cdn.rawgit.com/sdimkov/hubot-skype-web/master/doc/index.html

**Comment by rgrove** [comment]
@sdimkov Are you still having trouble reaching these URLs? They're working for me, and the CDN reports that all edge servers are returning 200s with the same content. We've had a few cases in the past where a single CDN edge node was returning bad data for a URL, but so far it doesn't look like that's happening here.

**Comment by sdimkov** [comment]
You have to click on the SkypeWebAdapter (on the left) to see the 404.
![404](https://cloud.githubusercontent.com/assets/1939605/8490252/8077c61a-212e-11e5-8070-15fe0ab38cf5.PNG)

**Comment by rgrove** [comment]
It looks like that link points to https://cdn.rawgit.com/sdimkov/hubot-skype-web/v0.9.4/doc/class/SkypeWebAdapter.html

However, no such file exists in your GitHub repo as far as I can tell. The direct GitHub source URL is also a 404: https://github.com/sdimkov/hubot-skype-web/blob/v0.9.4/doc/class/SkypeWebAdapter.html

And the file `SkypeWebAdapter.html` doesn't appear in the directory listing here: https://github.com/sdimkov/hubot-skype-web/tree/v0.9.4/doc/class

Are you sure you committed this file?

**Comment by sdimkov** [comment]
You're correct! Totally my mistake. I missed that file.

..closing the issue
