### ISSUE TITLE
i didn't know i was using rawgit.com

### ISSUE THREAD

**Issue by lizgoodwin** [rgrove/rawgit#76]
i have the issue saying i need to change to cdn.rawgit but i have no idea how and didn't know i was using rawgit?? please help me!!!! error message across the screen of blog and won't disappear

**Comment by rgrove** [comment]
Your blog may be using a third-party theme that's loading CSS or JS from rawgit.com. View the source of the page that's displaying this message and search for "rawgit.com". Replace any references to "rawgit.com" with "cdn.rawgit.com". You may want to contact the author of your blog's theme as well.

If you didn't set up your blog, please contact the person who did and ask them to fix this.
