### ISSUE TITLE
URL formatter decodes previously encoded `#` characters

### ISSUE THREAD

**Issue by AndreyTretyak** [rgrove/rawgit#80]
I've tried to create link to file in brunch with name 'phase# 1', silly name I know that :) but I always giving me `404 error`.
For same file in master brunch it`s works perfectly.
Here is link to the repository if you need something to test on 
https://github.com/AndreyTretyak/SpreadsheetSimulator

**Comment by rgrove** [comment]
Howdy @AndreyTretyak. This looks like a bug in the URL formatter on RawGit's homepage. It's not properly encoding the `#` character in the URL. Thanks for letting me know!

Until I get this fixed, you can work around the problem by replacing the `#` character in your URLs with `%23`. For example: https://rawgit.com/AndreyTretyak/SpreadsheetSimulator/phase%231/README.md
