### ISSUE TITLE
RawGit CDN breaking minified code?

### ISSUE THREAD

**Issue by dsl101** [rgrove/rawgit#82]
I've been using [clipboard.js](https://github.com/zenorocha/clipboard.js) via RawGit and recently [reported a problem](https://github.com/zenorocha/clipboard.js/issues/92) there. Turns out the problem is _only_ when accessing via RawGit - the other CDNs work fine.

Obviously I can easily switch (and have done), but I thought you might like to know - I really have no idea what's causing it, but, well, there it is :). I think it should be _relatively_ simple to set up a fiddle to reproduce the problem if that's of interest?

**Comment by rgrove** [comment]
Yes, if you could set up a reproducible test case to demonstrate the problem, that'd be great! I'm on the road today, but I can investigate tomorrow.

**Comment by dsl101** [comment]
In case of TLDR, I think this is a version problem. A change committed by the author 16 days ago isn't in the version coming from rawgit. I have no idea who needs to do what about that! If you want to look for it, I diffed the min versions between rawgit and cdnjs, and the key change is at offset 3645 (character not line) - it should read 'textarea' not 'input'. See [here](https://github.com/zenorocha/clipboard.js/pull/38).

Before realising that, I'd typed this:

OK, I made a fiddle. Working version, using cdnjs.com:

http://jsfiddle.net/qwwkbo5w/4

broken version using rawgit:

http://jsfiddle.net/ruh1uxq9/

The only difference is which source the external library comes from. To see in action, click the 'click me' label (nothing will appear to happen), but your clipboard should be loaded with the text from the `<td>` element, and it should have a line break in it. If you open the console, you can see the JS printing out the contents of the string, and there should be an ASCII 10 in the middle on both versions. But the action code from the library then mangles it in the rawgit version.

**Comment by rgrove** [comment]
Ah. This isn't a bug, this is the CDN permanently caching files based on their URL, as it should. CDN URLs should use commit refs or tags, not branches, as explained in [this FAQ answer](http://rawgit.com/faq#cdn-ttl).
