### ISSUE TITLE
CDN hanging

### ISSUE THREAD

**Issue by brauliobo** [rgrove/rawgit#85]
On http://webodf.org/demos/invoice-generator/#invoice.fodt, `rawgit` completely hangs on `https://cdn.rawgit.com/google/closure-library/97e8a0c0fc7238a56cc4dacd4a96fd4c0735b992/closure/goog/css/popupdatepicker.css` and others sources from the same repo

**Comment by rgrove** [comment]
This seems to be working fine for me from the western US, but I have seen cases in the past where specific CDN nodes in one geographic region have temporary problems that other regions don't have. If you can tell me where you're located (city and country), that might help me track down the misbehaving CDN node if there is one.

**Comment by brauliobo** [comment]
Yeah, it finally loaded after several minutes hanging. I'm located at Mata de São João, Bahia, Brazil.
Thanks!

**Comment by rgrove** [comment]
Thanks for the info, and sorry about that!
