### ISSUE TITLE
For github enterprise authentication is required when rawgit approaches

### ISSUE THREAD

**Issue by kimshinelove** [rgrove/rawgit#89]
In raw git github enterprise you can not have access to the raw file. This is because the certificate is due to enter into essential raw file, as shown below each token is being generated.

![2015-11-27 9 56 07](https://cloud.githubusercontent.com/assets/1567151/11432250/1d9eb28c-94ed-11e5-9728-a95af1ffeda2.png)

So, feature personal access token by using the function seems to be better when the http authentication 
function is added on github.

Please review.

**Comment by rgrove** [comment]
Thanks for the info!

I'd prefer to keep RawGit focused on public GitHub repositories and public/secret gists hosted on github.com. I don't have the time or desire to maintain features for GitHub Enterprise, but if you're interested in providing that functionality in a RawGit fork, please feel free.

**Comment by kimshinelove** [comment]
Tnakns for your comment!
