### ISSUE TITLE
paper-input relative url not working

### ISSUE THREAD

**Issue by pkgulati** [rgrove/rawgit#90]
If I use following URL
<link rel="import" href="https://raw.githubusercontent.com/Polymer/paper-input/master/paper-input.html">
It will give error 
as internally paper-input uses polymer.html and other files as relative url
So it will try
https://raw.githubusercontent.com/Polymer/paper-input/polymer/polymer.html
which is not valid
Valid URL for polymer is 
https://raw.githubusercontent.com/Polymer/polymer/master/polymer.html

So issue is branch name master has come in between.

**Comment by rgrove** [comment]
This sounds like an issue with paper-input, not RawGit.
