### ISSUE TITLE
Ability to fetch files from private repos

### ISSUE THREAD

**Issue by wolfy1339** [rgrove/rawgit#92]
I currently try to use the rawgit service to fetch some CSS files from a private repsitory, but it won't work under rawgit because i keep getting 404 errors
The raw link GitHub provides looks as follows
<pre>raw.githubusercontent.com/&lt;username&gt;/&lt;repository&gt;/&lt;file name&gt;?token=&lt;token&gt;</pre>
And so I would appreciate if this feature was added.

**Comment by neoascetic** [comment]
See #89, #62 and #44. It is wontfix. But if you still need this, take a look at [rawgithack](https://raw.githack.com), it supports any GET parameter passing.

**Comment by wolfy1339** [comment]
Thanks for the info. I'll try using a private gist then
