### ISSUE TITLE
Support for raw files with token

### ISSUE THREAD

**Issue by IonicaBizau** [rgrove/rawgit#93]
For private repos, if we click the <kbd>Raw</kbd> button we are redirected to a url having the `token` parameter.

Would be probably handy to interpret it.

Example:

> `https://raw.githubusercontent.com/owner/repo/master/path/to/file.js?token=xxxxxx`

**Comment by neoascetic** [comment]
#92, #89, #62 and #44

**Comment by IonicaBizau** [comment]
@neoascetic Oh, got it. Anyway, it's not that important. :joy: Thanks!
