### ISSUE TITLE
loader3.gif in toolbar.js not found?

### ISSUE THREAD

**Issue by max-maxymenko** [rgrove/rawgit#94]
Hey guys thanks for doing a great job and making my site running nice and smooth :) 
The issue that I have found is this ( http://i.imgur.com/RlbLFHg.png ) - toolbar.js can't load the image?

Any thoughts? Thanks :+1:

**Comment by neoascetic** [comment]
URL is incorrect. Neither username nor repo was specified. Probably you need to use relative URLs to assets.

**Comment by max-maxymenko** [comment]
Thanks for the quick reply, just found an unknown resource in my css file :/
