### ISSUE TITLE
Installing rawgit dependencies (nodejs and npm) is non-trivial on Debian systems

### ISSUE THREAD

**Issue by bgilmer77** [rgrove/rawgit#97]
It turns out that it, due to outdated code in current packages, installing nodejs and npm (step 1 in the installation instructions) is a PITA (not particularly complex, but it is a pain) on Debian systems.  I have figured out how to do it, and I am working on making a simple 'recipe' that will simplify this.  Would you be interested in having this as a contribution?  If so, how would you like me to contribute this?

**Comment by rgrove** [comment]
Thanks for offering! I don't think these instructions belong in the RawGit documentation though, since they're not specific to RawGit. I'm sure it'd make good fodder for a helpful blog post though.
