### ISSUE TITLE
Chrome is rejecting raw.githubusercontent.com due to "HSTS"

### ISSUE THREAD

**Issue by chicks-net** [rgrove/rawgit#98]
When I go to https://raw.githubusercontent.com/chicks-net/life-graphs/master/Dash/steam_community.png in Chrome Version 47.0.2526.106 (64-bit) on MacOSX and latest Firefox on CentOS7 it tells me:

> # Your connection is not private

> Attackers might be trying to steal your information from raw.githubusercontent.com (for example, passwords, messages, or credit cards). NET::ERR_CERT_AUTHORITY_INVALID
>  Automatically report details of possible security incidents to Google. Privacy policy

> ## Advanced
> raw.githubusercontent.com normally uses encryption to protect your information. When Chrome tried to connect to raw.githubusercontent.com this time, the website sent back unusual and incorrect credentials. Either an attacker is trying to pretend to be raw.githubusercontent.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chrome stopped the connection before any data was exchanged.

> You cannot visit raw.githubusercontent.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

This started yesterday for me.

**Comment by neoascetic** [comment]
Is it Github issue, isn't it?

**Comment by rgrove** [comment]
Yes, raw.githubusercontent.com is GitHub, not RawGit.

**Comment by rafoid** [comment]
The issue is closed but what's the solution??? Still can't get raw files from GitHub!

**Comment by rgrove** [comment]
@rafoid githubusercontent.com is a GitHub domain. It has nothing to do with RawGit. If you're experiencing a problem with it, you need to talk to GitHub.
