### ISSUE TITLE
Allow GitHub gists

### ISSUE THREAD

**Issue by llamasoft** [rgrove/rawgit#99]
Sometimes when I'm testing a personal script I don't want to make a full repository, just a quick [GitHub gist](https://gist.github.com/).  
It would be handy if rawgit supported gists.

**Comment by rgrove** [comment]
You're in luck! RawGit does support gists.

To get the raw URL for a file in a gist, just click the "Raw" button next to the file and copy the URL from the address bar:

<img width="1007" alt="160225pbw5v" src="https://cloud.githubusercontent.com/assets/1465/13340467/58b27fc2-dbe5-11e5-9f8e-01c3bd5714be.png">

Then paste that URL into RawGit to generate RawGit URLs:

<img width="1002" alt="160225smq4a" src="https://cloud.githubusercontent.com/assets/1465/13340493/8ae49d4a-dbe5-11e5-8d36-13a61f2f6c34.png">

**Comment by llamasoft** [comment]
Sorry about the false alarm!  
I was right-clicking the Raw button and using "Copy link location".  When you go that route, the domain is "gist.github.com" (which is considered invalid) but accessing the raw script forwards to "gist.githubusercontent.com".

**Comment by rgrove** [comment]
Whoops! You're right, that's confusing. Should be fixed now.
